CREATE TABLE dbo.Users (
    id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    phone NVARCHAR(20) NOT NULL UNIQUE,
    email NVARCHAR(255) NULL UNIQUE,
    name NVARCHAR(100) NOT NULL,
    password NVARCHAR(255) NOT NULL,
    role NVARCHAR(30) NOT NULL CHECK (role IN ('CUSTOMER','RESTAURANT_OWNER','ADMIN')),
    avatar NVARCHAR(1024) NULL,
    loyaltyPoints INT NOT NULL DEFAULT 0,
    createdAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    updatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
  );